// Code generated by go-mir. DO NOT EDIT.

package api

import (
	gin "github.com/gin-gonic/gin"
)

type Container interface {
	ListContainer(*gin.Context)
	NewContainer(*gin.Context)
	StartContainer(*gin.Context)
	RestartContainer(*gin.Context)
	StopContainer(*gin.Context)
	RemoveContainer(*gin.Context)
	ContainerInfo(*gin.Context)
	ContainerPartLog(*gin.Context)
	ContainerAllLog(*gin.Context)
}

// RegisterContainerServant register Container servant to gin
func RegisterContainerServant(e *gin.Engine, s Container) {
	router := e

	// register routes info to router
	router.Handle("GET", "/api/container", s.ListContainer)
	router.Handle("GET", "/api/container/run", s.NewContainer)
	router.Handle("GET", "/api/container/start/:containerId", s.StartContainer)
	router.Handle("GET", "/api/container/restart/:containerId", s.RestartContainer)
	router.Handle("GET", "/api/container/stop/:containerId", s.StopContainer)
	router.Handle("GET", "/api/container/delete/:containerId", s.RemoveContainer)
	router.Handle("GET", "/api/container/info/:containerId", s.ContainerInfo)
	router.Handle("GET", "/api/container/log/part/:containerId", s.ContainerPartLog)
	router.Handle("GET", "/api/container/log/all/:containerId", s.ContainerAllLog)
}
