// Code generated by go-mir. DO NOT EDIT.

package api

import (
	gin "github.com/gin-gonic/gin"
)

type Docker interface {
	DockerInfo(*gin.Context)
	VersionInfo(*gin.Context)
	Ping(*gin.Context)
}

// RegisterDockerServant register Docker servant to gin
func RegisterDockerServant(e *gin.Engine, s Docker) {
	router := e

	// register routes info to router
	router.Handle("GET", "/api/docker/info", s.DockerInfo)
	router.Handle("GET", "/api/docker/version", s.VersionInfo)
	router.Handle("GET", "/api/docker/ping", s.Ping)
}
