// Code generated by go-mir. DO NOT EDIT.

package api

import (
	gin "github.com/gin-gonic/gin"
)

type Image interface {
	ListImage(*gin.Context)
	ImageInfo(*gin.Context)
	DeleteImage(*gin.Context)
	TagImage(*gin.Context)
	SaveImage(*gin.Context)
	PullImage(*gin.Context)
}

// RegisterImageServant register Image servant to gin
func RegisterImageServant(e *gin.Engine, s Image) {
	router := e

	// register routes info to router
	router.Handle("GET", "/api/image", s.ListImage)
	router.Handle("GET", "/api/image/info/:imageId", s.ImageInfo)
	router.Handle("GET", "/api/image/remove/:imageId/:forge", s.DeleteImage)
	router.Handle("GET", "/api/image/tag", s.TagImage)
	router.Handle("GET", "/api/image/save/:imageId", s.SaveImage)
	router.Handle("GET", "/api/image/pull", s.PullImage)
}
