// Code generated by go-mir. DO NOT EDIT.

package api

import (
	"net/http"

	gin "github.com/gin-gonic/gin"
)

type Portal interface {
	Index(*gin.Context)
	GetMainAssets(*gin.Context)
	GetCSSAssets(*gin.Context)
	HeadCSSAssets(*gin.Context)
	GetJSAssets(*gin.Context)
	HeadJSAssets(*gin.Context)

	mustEmbedUnimplementedPortalServant()
}

// RegisterPortalServant register Portal servant to gin
func RegisterPortalServant(e *gin.Engine, s Portal) {
	router := e

	// register routes info to router
	router.Handle("GET", "/", s.Index)
	router.Handle("GET", "/index.html", s.GetMainAssets)
	router.Handle("GET", "/css/*filepath", s.GetCSSAssets)
	router.Handle("HEAD", "/css/*filepath", s.HeadCSSAssets)
	router.Handle("GET", "/js/*filepath", s.GetJSAssets)
	router.Handle("HEAD", "/js/*filepath", s.HeadJSAssets)
}

// UnimplementedPortalServant can be embedded to have forward compatible implementations.
type UnimplementedPortalServant struct {
}

func (UnimplementedPortalServant) Index(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method Index not implemented")
}

func (UnimplementedPortalServant) GetMainAssets(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method GetMainAssets not implemented")
}

func (UnimplementedPortalServant) GetCSSAssets(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method GetCSSAssets not implemented")
}

func (UnimplementedPortalServant) HeadCSSAssets(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method HeadCSSAssets not implemented")
}

func (UnimplementedPortalServant) GetJSAssets(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method GetJSAssets not implemented")
}

func (UnimplementedPortalServant) HeadJSAssets(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method HeadJSAssets not implemented")
}

func (UnimplementedPortalServant) mustEmbedUnimplementedPortalServant() {}
