// Code generated by go-mir. DO NOT EDIT.

package api

import (
	gin "github.com/gin-gonic/gin"
)

type Portal interface {
	Index(*gin.Context)
	GetMainAssets(*gin.Context)
	GetCSSAssets(*gin.Context)
	HeadCSSAssets(*gin.Context)
	GetJSAssets(*gin.Context)
	HeadJSAssets(*gin.Context)
}

// RegisterPortalServant register Portal servant to gin
func RegisterPortalServant(e *gin.Engine, s Portal) {
	router := e

	// register routes info to router
	router.Handle("GET", "/", s.Index)
	router.Handle("GET", "/index.html", s.GetMainAssets)
	router.Handle("GET", "/css/*filepath", s.GetCSSAssets)
	router.Handle("HEAD", "/css/*filepath", s.HeadCSSAssets)
	router.Handle("GET", "/js/*filepath", s.GetJSAssets)
	router.Handle("HEAD", "/js/*filepath", s.HeadJSAssets)
}
