// Code generated by go-mir. DO NOT EDIT.

package api

import (
	"net/http"

	gin "github.com/gin-gonic/gin"
)

type Portal interface {
	Index(*gin.Context)
	IndexHtml(*gin.Context)
	CSSAssets(*gin.Context)
	JSAssets(*gin.Context)

	mustEmbedUnimplementedPortalServant()
}

// RegisterPortalServant register Portal servant to gin
func RegisterPortalServant(e *gin.Engine, s Portal) {
	router := e

	// register routes info to router
	router.Handle("GET", "/", s.Index)
	router.Handle("GET", "/index.html", s.IndexHtml)
	router.Handle("HEAD", "/css/*filepath", s.CSSAssets)
	router.Handle("GET", "/css/*filepath", s.CSSAssets)

	router.Handle("GET", "/js/*filepath", s.JSAssets)
}

// UnimplementedPortalServant can be embedded to have forward compatible implementations.
type UnimplementedPortalServant struct {
}

func (UnimplementedPortalServant) Index(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method Index not implemented")
}

func (UnimplementedPortalServant) IndexHtml(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method IndexHtml not implemented")
}

func (UnimplementedPortalServant) CSSAssets(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method CSSAssets not implemented")
}

func (UnimplementedPortalServant) JSAssets(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method JSAssets not implemented")
}

func (UnimplementedPortalServant) mustEmbedUnimplementedPortalServant() {}
