// Code generated by go-mir. DO NOT EDIT.

package api

import (
	gin "github.com/gin-gonic/gin"
)

type Volume interface {
	GetVolumeList(*gin.Context)
	NewVolume(*gin.Context)
	GetVolumeInfo(*gin.Context)
	RemoveVolume(*gin.Context)
	PruneVolume(*gin.Context)
}

// RegisterVolumeServant register Volume servant to gin
func RegisterVolumeServant(e *gin.Engine, s Volume) {
	router := e

	// register routes info to router
	router.Handle("GET", "/api/volume", s.GetVolumeList)
	router.Handle("GET", "/api/volume/new", s.NewVolume)
	router.Handle("GET", "/api/volume/info/:volumeId", s.GetVolumeInfo)
	router.Handle("GET", "/api/volume/delete/:volumeId/:force", s.RemoveVolume)
	router.Handle("GET", "/api/volume/prune", s.PruneVolume)
}
