// Code generated by go-mir. DO NOT EDIT.

package api

import (
	"net/http"

	gin "github.com/gin-gonic/gin"
)

type Volume interface {
	ListVolume(*gin.Context)
	CreateVolume(*gin.Context)
	VolumeInfo(*gin.Context)
	RemoveVolume(*gin.Context)
	PruneVolume(*gin.Context)

	mustEmbedUnimplementedVolumeServant()
}

// RegisterVolumeServant register Volume servant to gin
func RegisterVolumeServant(e *gin.Engine, s Volume) {
	router := e

	// register routes info to router
	router.Handle("GET", "/api/volume", s.ListVolume)
	router.Handle("GET", "/api/volume/new", s.CreateVolume)
	router.Handle("GET", "/api/volume/info/:volumeId", s.VolumeInfo)
	router.Handle("GET", "/api/volume/delete/:volumeId/:force", s.RemoveVolume)
	router.Handle("GET", "/api/volume/prune", s.PruneVolume)
}

// UnimplementedVolumeServant can be embedded to have forward compatible implementations.
type UnimplementedVolumeServant struct {
}

func (UnimplementedVolumeServant) ListVolume(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method ListVolume not implemented")
}

func (UnimplementedVolumeServant) CreateVolume(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method CreateVolume not implemented")
}

func (UnimplementedVolumeServant) VolumeInfo(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method VolumeInfo not implemented")
}

func (UnimplementedVolumeServant) RemoveVolume(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method RemoveVolume not implemented")
}

func (UnimplementedVolumeServant) PruneVolume(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method PruneVolume not implemented")
}

func (UnimplementedVolumeServant) mustEmbedUnimplementedVolumeServant() {}
