// Code generated by go-mir. DO NOT EDIT.

package api

import (
	gin "github.com/gin-gonic/gin"
)

type Volume interface {
	ListVolume(*gin.Context)
	CreateVolume(*gin.Context)
	VolumeInfo(*gin.Context)
	RemoveVolume(*gin.Context)
	PruneVolume(*gin.Context)
}

// RegisterVolumeServant register Volume servant to gin
func RegisterVolumeServant(e *gin.Engine, s Volume) {
	router := e

	// register routes info to router
	router.Handle("GET", "/api/volume", s.ListVolume)
	router.Handle("GET", "/api/volume/new", s.CreateVolume)
	router.Handle("GET", "/api/volume/info/:volumeId", s.VolumeInfo)
	router.Handle("GET", "/api/volume/delete/:volumeId/:force", s.RemoveVolume)
	router.Handle("GET", "/api/volume/prune", s.PruneVolume)
}
